name: Deploy
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Prebuilt
        run: npm run prebuilt
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          cname: codergosha.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
